In [1]:
import requests
from bs4 import BeautifulSoup
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

url = "https://www.equitymaster.com/india-markets/nse-replica.asp"
r = requests.get(url) # r variable has all the HTML code
htmlContent = r.content # r returns response so if we want the code we write r.content
# print(htmlContent)

htmlText = r.text
# print(htmlText)

soup = BeautifulSoup(r.content, 'html.parser')

# Assuming `soup` is your BeautifulSoup object containing the HTML
table_data = []
col_name = []

# Loop through each table with the specified class
for i in soup.find_all("table", class_="mystocksbig mystocks newtab cls"):
    rows = i.find_all('tr')  # Find all rows in the table
    for row in rows:
        cols = row.find_all('th')  # Find all columns (th elements)
        cols = [col.text.strip() for col in cols]  # Extract text and remove extra spaces
        col_name.append(cols)
        cols = row.find_all('td')  # Find all columns (td elements)
        cols = [col.text.strip() for col in cols]  # Extract text and remove extra spaces
        table_data.append(cols)  # Append the row data to the table_data list

col_name = col_name[1:3]
col_name = sum(col_name, []) # converting list of list to a single list
del col_name[6]

# Convert the list of lists into a pandas DataFrame
df = pd.DataFrame(data=table_data, columns=col_name)
df = df.dropna(subset="COMPANY").reset_index(drop = True)

print(df.head())
# df.to_csv('/content/drive/My Drive/AbhiData/output.csv', index=False)

Mounted at /content/drive
             COMPANY       INDUSTRY MARKET PRICE(Rs) CHANGE(%) NO OFSHARES(m)  \
0  ADANI ENTERPRISES  MISCELLANEOUS          3,009.1      -0.9        1,140.0
1  ADANI PORTS & SEZ  MISCELLANEOUS          1,469.0      -0.7        2,160.1
2   APOLLO HOSPITALS  MISCELLANEOUS          6,925.0       1.2          143.8
3       ASIAN PAINTS         PAINTS          3,228.7       2.3          959.2
4          AXIS BANK        BANKING          1,178.0      -1.1        3,092.2

  MARKET CAP.**(Rs m) FREE FLOAT ADJ. FACTOR# EARNINGS *(Rs m) EPS(Rs) PER(X)
0           3,430,377                     0.3           42,270    37.1   81.2
1           3,173,244                     0.3           92,554    42.8   34.3
2             995,709                     0.7           10,535    73.3   94.5
3           3,096,914                     0.5           50,306    52.4   61.6
4           3,642,508                     0.9          267,746    86.6   13.6

In [2]:
df

,COMPANY,INDUSTRY,MARKET PRICE(Rs),CHANGE(%),NO OFSHARES(m),MARKET CAP.**(Rs m),FREE FLOAT ADJ. FACTOR#,EARNINGS *(Rs m),EPS(Rs),PER(X)
0,ADANI ENTERPRISES,MISCELLANEOUS,"3,009.1",-0.9,"1,140.0","3,430,377",0.3,"42,270",37.1,81.2
1,ADANI PORTS & SEZ,MISCELLANEOUS,"1,469.0",-0.7,"2,160.1","3,173,244",0.3,"92,554",42.8,34.3
2,APOLLO HOSPITALS,MISCELLANEOUS,"6,925.0",1.2,143.8,"995,709",0.7,"10,535",73.3,94.5
3,ASIAN PAINTS,PAINTS,"3,228.7",2.3,959.2,"3,096,914",0.5,"50,306",52.4,61.6
4,AXIS BANK,BANKING,"1,178.0",-1.1,"3,092.2","3,642,508",0.9,"267,746",86.6,13.6
5,BAJAJ AUTO,AUTOMOBILES,"10,958.5",-0.8,279.3,"3,060,230",0.4,"77,328",276.9,39.6
6,BAJAJ FINANCE,FINANCE,"7,295.0",-0.8,620.0,"4,522,678",0.5,"149,189",240.6,30.3
7,BAJAJ FINSERV,FINANCE,"1,869.0",0.2,"1,596.7","2,984,161",0.4,"160,875",100.8,18.5
8,BHARTI AIRTEL,TELECOM,"1,557.5",-0.2,"6,085.3","9,477,815",0.5,"87,241",14.3,108.6
9,BPCL,ENERGY,358.0,0.7,"4,338.5","1,552,955",0.5,"180,878",41.7,8.6
10,CIPLA,PHARMACEUTICALS,"1,653.6",0.0,807.6,"1,335,381",0.7,"43,350",53.7,30.8
11,COAL INDIA,MINING,503.4,-3.1,"6,162.7","3,102,317",0.4,"349,559",56.7,8.9
12,DIVIS LABORATORIES,PHARMACEUTICALS,"5,076.1",0.2,265.5,"1,347,545",0.5,"16,740",63.1,80.5
13,DR. REDDYS LAB,PHARMACEUTICALS,"6,792.0",-0.9,166.9,"1,133,372",0.7,"55,490",332.5,20.4
14,EICHER MOTORS,AUTOMOBILES,"4,830.0",-0.7,274.1,"1,323,699",0.5,"36,623",133.6,36.1
15,GRASIM,TEXTILES,"2,755.1",1.8,680.6,"1,874,950",0.6,"94,966",139.5,19.7
16,HCL TECHNOLOGIES,SOFTWARE,"1,782.8",-0.4,"2,713.7","4,837,786",0.4,"164,380",60.6,29.4
17,HDFC BANK,BANKING,"1,640.8",0.2,"7,623.3","12,508,386",1.0,"702,313",92.1,17.8
18,HDFC LIFE INSURANCE,INSURANCE,758.4,-0.0,"2,151.5","1,631,688",0.5,"16,364",7.6,99.7
19,HERO MOTOCORP,AUTOMOBILES,"5,684.6",0.7,200.0,"1,136,807",0.7,"41,537",207.7,27.4
20,HINDALCO,ALUMINIUM,664.2,-2.2,"2,247.2","1,492,601",0.7,"107,730",47.9,13.9
21,HINDUSTAN UNILEVER,FMCG,"2,840.1",1.6,"2,349.6","6,673,074",0.4,"103,430",44.0,64.5
22,ICICI BANK,BANKING,"1,239.5",-0.7,"7,043.8","8,730,756",1.0,"466,493",66.2,18.7
23,INDUSIND BANK,BANKING,"1,433.6",-0.2,778.9,"1,116,662",0.8,"90,233",115.8,12.4
24,INFOSYS,SOFTWARE,"1,919.7",-1.1,"4,152.1","7,970,645",0.9,"266,770",64.2,29.9
25,IOC,ENERGY,177.0,0.5,"14,121.2","2,499,459",0.5,"303,705",21.5,8.2
26,ITC,FOOD & TOBACCO,507.4,-0.4,"12,505.5","6,344,658",1.0,"207,130",16.6,30.6
27,JSW STEEL,STEEL,931.8,0.1,"2,445.5","2,278,674",0.6,"75,620",30.9,30.1
28,KOTAK MAHINDRA BANK,BANKING,"1,786.2",0.1,"1,988.1","3,551,081",0.7,"212,669",107.0,16.7
29,L&T,ENGINEERING,"3,643.7",-1.3,"1,375.0","5,010,069",1.0,"158,937",115.6,31.5
30,LTIMINDTREE,SOFTWARE,"6,067.1",-1.3,296.2,"1,796,897",0.3,"45,674",154.2,39.3
31,M&M,AUTOMOBILES,"2,742.3",-1.5,"1,243.5","3,410,129",0.8,"109,472",88.0,31.2
32,MARUTI SUZUKI,AUTOMOBILES,"12,315.2",-0.7,314.4,"3,871,915",0.4,"144,336",459.1,26.8
33,NESTLE,FOOD & TOBACCO,"2,532.0",0.0,964.2,"2,441,198",0.4,"32,445",33.7,75.2
34,NTPC,POWER,404.2,-0.6,"9,696.7","3,918,908",0.5,"193,837",20.0,20.2
35,ONGC,ENERGY,312.8,-2.9,"12,580.3","3,934,482",0.4,"469,786",37.3,8.4
36,POWER GRID,POWER,332.4,-0.7,"9,300.6","3,091,056",0.5,"159,734",17.2,19.4
37,RELIANCE IND.,ENERGY,"3,025.0",0.2,"6,766.2","20,467,843",0.5,"778,990",115.1,26.3
38,SBI,BANKING,814.9,-1.2,"8,924.6","7,272,667",0.4,"690,831",77.4,10.5
39,SBI LIFE INSURANCE,INSURANCE,"1,912.9",-0.8,"1,001.8","1,916,321",0.4,"20,323",20.3,94.3
40,SHRIRAM FINANCE,FINANCE,"3,247.2",-0.7,376.0,"1,220,803",0.7,"76,606",203.8,15.9
41,SUN PHARMA,PHARMACEUTICALS,"1,832.7",1.2,"2,399.3","4,397,141",0.5,"105,067",43.8,41.9
42,TATA CONSUMER,FMCG,"1,195.1",-0.3,989.4,"1,182,387",0.7,"12,566",12.7,94.1
43,TATA MOTORS,AUTOMOBILES,"1,078.8",-0.6,"3,680.9","3,970,754",0.5,"335,803",91.2,11.8
44,TATA STEEL,STEEL,151.1,-0.7,"12,483.5","1,886,125",0.7,"-48,217",-3.9,-
45,TCS,SOFTWARE,"4,469.2",-1.0,"3,618.1","16,169,957",0.3,"470,840",130.1,34.3
46,TECH MAHINDRA,SOFTWARE,"1,642.6",-0.1,978.2,"1,606,763",0.6,"25,527",26.1,62.9
47,TITAN,RETAILING,"3,610.8",-0.3,887.8,"3,205,574",0.5,"34,540",38.9,92.8
48,ULTRATECH CEMENT,CEMENT,"11,539.8",0.7,288.7,"3,331,509",0.4,"69,878",242.0,47.7
49,WIPRO,SOFTWARE,518.0,-3.4,"5,231.1","2,709,706",0.3,"112,908",21.6,24.0
50,TOTAL,"172,489","203,638,337",,"8,473,904",Avg. PER,24.0,None,None,None